openapi: 3.0.1
info:
  title: caddy-jwt
  description: Cortex descriptor created automatically by eng-devprod
  x-cortex-tag: caddy-jwt
  x-cortex-type: service
  x-cortex-owners:
  - name: eng-train
    type: group
    provider: OKTA
    description: Updated by eng-devprod
  x-cortex-git:
    github:
      alias: cortex
      repository: cerebrotech/caddy-jwt
